---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lticatal/repositories/UIC-LTI-Catalog
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
